version: '3'

services:
  mongo:
    image: mongo
    container_name: HRMS-Mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"

  postgres:
    image: postgres:latest
    container_name: HRMS-Postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/populate_data.sql:/docker-entrypoint-initdb.d/populate_data.sql
