version: '3'

services:
  fastapi:
    build: .
    container_name: HRMS-FastAPI
    command: uvicorn hrms_back.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - mongo
      - postgres
      - redis
    ports:
      - "8000:8000"

  mongo:
    image: mongo
    container_name: HRMS-Mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"

  postgres:
    image: postgres:latest
    container_name: HRMS-Postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:5.0.8
    container_name: HRMS-Redis
    ports:
      - "6379:6379"