version: '3'

services:
  fastapi:
    build: .
    container_name: HRMS-FastAPI
    command: uvicorn hrms_back.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
    working_dir: /app
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - COOKIE=${COOKIE}
      - COOKIE_NAME=${COOKIE_NAME}
      - COOKIE_MAX_AGE=${COOKIE_MAX_AGE}
      - KEY_PREFIX_REDIS_STRATEGY=${KEY_PREFIX_REDIS_STRATEGY}
      - USER_ID_REDIS_STRATEGY=${USER_ID_REDIS_STRATEGY}
      - ROLE_REDIS_STRATEGY=${ROLE_REDIS_STRATEGY}
      - PATIENT=${PATIENT}
      - DOCTOR=${DOCTOR}
      - ADMIN=${ADMIN}
    depends_on:
      - mongo
      - postgres
      - redis
    ports:
      - "8000:8000"

  mongo:
    image: mongo
    container_name: HRMS-Mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"

  postgres:
    image: postgres:latest
    container_name: HRMS-Postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:5.0.8
    container_name: HRMS-Redis
    ports:
      - "6379:6379"